### ISSUE TITLE
No warning for corrupt files

### ISSUE THREAD

**Issue by tristanpoland** [Gameplex-Software/SkiffUI#14]
There is no warning for corrupt files, they can crash the program, or simply open a blank unusable graph.

**Comment by WilliamAnimate** [comment]
i have no idea how corrupt files work, but i'll assume (for this case) the entire file is completely screwed up
in the first few bytes of the file, there will be bytes to mark it as "not corrupted"

and just in case only like 1/4 of the file is corrupt, we just use the python equalivant (cant spell) of a try{} loop

**Comment by tristanpoland** [comment]
What I will probably end up doing is a simple Try-catch (try except in Python) so that when it loads the file if it encounters any errors it catches them by simply creating a pop up that says that the file is corrupt.

**Comment by tristanpoland** [comment]
Issue was resolved
