### ISSUE TITLE
Proper installer for the final version?

### ISSUE THREAD

**Issue by tristanpoland** [Gameplex-Software/SkiffUI#64]

**Comment by WilliamAnimate** [comment]
i think we can have a file that installs python (3.8) for you, and then downloads the program?

there might be 2 problems with my idea however:
- the installer wont be able to be written in python
- "write once, debug everywhere"

**Comment by tristanpoland** [comment]
Yes, this is certainly an option we could consider. There are some packager programs too but they don't play nice with the existing code. The one included in the source code creates an EXE successfully byt it will not launch properly.
